global:
  image: {}
  rollingUpdate: {}

image: 
  name: "data61/magda-minion-format"
  # repository: 
  # tag: 
  # pullPolicy: 
  # imagePullSecret: 

defaultImage:
  repository: docker.io
  tag: 0.0.57-0
  pullPolicy: IfNotPresent
  # imagePullSecret: ""

defaultAdminUserId: "00000000-0000-4000-8000-000000000000"

resources:
  requests:
    cpu: 10m
    memory: 30Mi
  limits:
    cpu: 100m